global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: quickserve-cloud-backend
    metrics_path: /api/actuator/prometheus
    static_configs:
      - targets: ["cloud-backend:8080"]

  - job_name: quickserve-edge-backend
    metrics_path: /api/actuator/prometheus
    static_configs:
      - targets: ["edge-backend:8081"]
